name: dart_application_2
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  json_serializable: ^6.1.4
  validators: ^3.0.0
  dolumns: ^2.0.0
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^1.0.0
  test: ^1.16.0